version: '3.8'

services:
  api-gateway:
    container_name: auth_service 
    build: ./
    ports:
      - "8083:8083"
    networks:
      - global-network
    depends_on:
      - redis
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    environment:
      REDIS_PASSWORD: "root"
    networks:
      - global-network
# Docker Networks
networks:
  global-network:
    external: true 
